from os import environ

FLASK_ENV = environ.get('FLASK_ENV')
SQLALCHEMY_DATABASE_URI = environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
SHOW_SQLALCHEMY_LOG_MESSAGES = environ.get('SHOW_SQLALCHEMY_LOG_MESSAGES')
SQLALCHEMY_ECHO = environ.get('SQLALCHEMY_ECHO')